### ISSUE TITLE
Getting error- "Can't open "/data/user/0/melonizippo.org.facerecognition/cache/caffe_model/resnet50_ft_caffe/resnet50_ft.caffemodel""

### ISSUE THREAD

**Issue by PriyaSindkar** [MeloniZippoProjects/MultimediaProject#1]
Hi, I am running the project as it is from android studio and getting an exception about not finding 'resnet50_ft.caffemodel'

Here is the stacktrace-

```
E/cv::error(): OpenCV(3.4.1) Error: Unspecified error (FAILED: fs.is_open(). Can't open "/data/user/0/melonizippo.org.facerecognition/cache/caffe_model/resnet50_ft_caffe/resnet50_ft.caffemodel") in bool cv::dnn::ReadProtoFromBinaryFile(const char*, google::protobuf::Message*), file /build/master_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1126
2019-08-08 10:41:11.911 5421-5421/? E/org.opencv.dnn: dnn::readNetFromCaffe_10() caught cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp:1126: error: (-2) FAILED: fs.is_open(). Can't open "/data/user/0/melonizippo.org.facerecognition/cache/caffe_model/resnet50_ft_caffe/resnet50_ft.caffemodel" in function bool cv::dnn::ReadProtoFromBinaryFile(const char*, google::protobuf::Message*)
2019-08-08 10:41:11.915 5421-5421/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: melonizippo.org.facerecognition, PID: 5421
    java.lang.RuntimeException: Unable to create application melonizippo.org.facerecognition.FaceRecognitionApp: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp:1126: error: (-2) FAILED: fs.is_open(). Can't open "/data/user/0/melonizippo.org.facerecognition/cache/caffe_model/resnet50_ft_caffe/resnet50_ft.caffemodel" in function bool cv::dnn::ReadProtoFromBinaryFile(const char*, google::protobuf::Message*)
    ]
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6112)
        at android.app.ActivityThread.access$1200(ActivityThread.java:212)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1806)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
     Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp:1126: error: (-2) FAILED: fs.is_open(). Can't open "/data/user/0/melonizippo.org.facerecognition/cache/caffe_model/resnet50_ft_caffe/resnet50_ft.caffemodel" in function bool cv::dnn::ReadProtoFromBinaryFile(const char*, google::protobuf::Message*)
    ]
        at org.opencv.dnn.Dnn.readNetFromCaffe_0(Native Method)
        at org.opencv.dnn.Dnn.readNetFromCaffe(Dnn.java:107)
        at melonizippo.org.facerecognition.deep.DNNExtractor.<init>(DNNExtractor.java:26)
        at melonizippo.org.facerecognition.FaceRecognitionApp.initFaceRecognition(FaceRecognitionApp.java:94)
        at melonizippo.org.facerecognition.FaceRecognitionApp.onCreate(FaceRecognitionApp.java:70)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1176)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6107)
        	... 8 more
```

Do I have to train the model myself and generate the said file?

**Comment by PriyaSindkar** [comment]
Error solved. I had forgotten to include the unzipped files from the 7zip that included the said file.

**Comment by enricomeloni** [comment]
Hi Priya, you reached the solution before we could see your issue, good job!

If you have any other problems or questions about the project, do not hesitate to write us! :)

**Comment by PriyaSindkar** [comment]
Also, I was wondering if there is a way in which I can compress the resnet50.caffemodel?
